"""added profile pic

Revision ID: 26775fd0e8c6
Revises: 46eee015b269
Create Date: 2024-10-16 22:47:38.276087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26775fd0e8c6'
down_revision = '46eee015b269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
