"""About Author

Revision ID: 46eee015b269
Revises: 18a471816494
Create Date: 2024-10-16 21:39:26.185407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46eee015b269'
down_revision = '18a471816494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
